security:
    oauth2:
#    https://dev-749812.oktapreview.com
#   Client-Id = 0oah20iuq4Be0OQJb0h7

        client:
            access-token-uri: https://dev-749812.oktapreview.com/oauth2/default/v1/token
            user-authorization-uri: https://dev-749812.oktapreview.com/oauth2/default/v1/authorize
            client-id: 0oah20iuq4Be0OQJb0h7
            scope: openid profile email
        resource:
            user-info-uri: https://dev-749812.oktapreview.com/oauth2/default/v1/userinfo
            token-info-uri: https://dev-749812.oktapreview.com/oauth2/default/v1/introspect
            prefer-token-info: false
            
# spring.h2.console.enabled=false # Whether to enable the console.       
#spring:
#  h2:
#    console:
#      enabled: true            